// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gecnenqiflcozadcrhlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlY25lbnFpZmxjb3phZGNyaGxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTUyODAsImV4cCI6MjA1ODgzMTI4MH0.uZTVlOUqxoESsGL5fCuWcW-Xe9z6DAxWrnsA4zK4mic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);